- src/components/gauge-chart/gauge-chart.ts
- src/core/plugins/plugin-types.ts
Description: When I change the size of the browser window, the chart is not adaptive.
> fix(gauge) : fix gauge chart resize issue

- package-lock.json
- package.json
- site/index.html
- src/components/gauge-chart/gauge-chart.options.ts
- src/components/gauge-chart/gauge-chart.plugins.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/gauge-chart/gauge-chart.types.ts
- src/components/hello-chart/hello-chart.ts
- src/components/index.ts
- src/components/pie-chart/index.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.plugins.ts
- src/components/pie-chart/pie-chart.ts
- src/components/pie-chart/pie-chart.types.ts
- src/core/common/chart.types.ts
- src/core/common/global-style.ts
- src/core/plugins/chart-legend-a11y.ts
- src/core/plugins/index.ts
- src/core/plugins/legend-plugins.ts
- src/core/plugins/plugin.types.ts
> add pie chart type 
> pie chart can support legend filter by config
> feat(pie):  pie chart type and legend clickable

- site/index.html
- src/components/gauge-chart/gauge-chart.options.ts
- src/components/gauge-chart/gauge-chart.plugins.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/gauge-chart/gauge-chart.types.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.plugins.ts
- src/components/pie-chart/pie-chart.ts
- src/components/pie-chart/pie-chart.types.ts
- src/core/common/chart.types.ts
- src/core/plugins/legend-plugins.ts
> Refactor data structure
> Support  customize pie chart center  value and legend style
> refactor(pie): adjust the data structure to support multiple data

- src/components/gauge-chart/gauge-chart.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.ts
- src/core/chart-options.ts
- src/types/chart.types.ts
> code change for chart get global theme.
> fix(pie): code change for chart get global theme

- site/index.html
- src/components/gauge-chart/gauge-chart.options.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.plugins.ts
- src/components/pie-chart/pie-chart.ts
- src/core/chart-options.ts
- src/core/plugins/chart-tooltip.ts
- src/core/plugins/legend-plugins.ts
- src/styles/internal-style.ts
- src/types/chart.types.ts
develop can customize chart tooltip and legend tooltip
> feat(tooltip): support chart tooltip and legend tooltip customization

- site/index.html
- src/components/gauge-chart/gauge-chart.plugins.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/hello-chart/hello-chart.ts
- src/components/pie-chart/pie-chart.plugins.ts
- src/components/pie-chart/pie-chart.ts
- src/core/plugins/chart-a11y.ts
- src/core/plugins/chart-event.ts
- src/core/plugins/chart-legend-a11y.ts
- src/core/plugins/chart-tooltip.ts
- src/core/plugins/index.ts
- src/core/plugins/legend-plugins.ts
adjust default tooptip templete
> fix(tooltip): adjust default tooltip templete

- package-lock.json
- package.json
- src/components/pie-chart/pie-chart.plugins.ts
- src/components/pie-chart/pie-chart.ts
- src/core/plugins/chart-tooltip.ts
- src/core/plugins/legend-plugins.ts
>Support converting the entire chart to canvas
>Fix issues with the center label, chart resize, and click the legend
> fix(pie): support converting the entire chart to canvas

- site/index.html
- src/components/gauge-chart/gauge-chart.ts
- src/components/pie-chart/pie-chart.ts
- src/core/plugins/chart-legend-a11y.ts
- src/types/chart.types.ts
- website/docs/tutorials/doughnut.mdx
- website/docs/tutorials/gauge.mdx
- website/docs/tutorials/pie.mdx
> docs: examples for guage and pie charts

- src/components/xy-chart/xy-chart.ts
- src/core/utils.ts
>Supports conversion between table data and JSON.
> refactor(utils): supports conversion between table data and JSON

- src/lib/area/area.ts
- src/lib/area/area.types.ts
- src/lib/area/index.ts
- src/lib/bar/bar.ts
- src/lib/bar/bar.types.ts
- src/lib/bar/index.ts
- src/lib/charts.ts
- src/lib/column/column.ts
- src/lib/column/column.types.ts
- src/lib/column/index.ts
- src/lib/line/index.ts
- src/lib/line/line.ts
- src/lib/line/line.types.ts
- src/lib/range/index.ts
- src/lib/range/range.ts
- src/lib/range/range.types.ts
- src/lib/xy/index.ts
- src/lib/xy/xy.options.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- website/docs/tutorials/demo-charts/area.mdx
- website/docs/tutorials/demo-charts/bar.mdx
- website/docs/tutorials/demo-charts/column.mdx
- website/docs/tutorials/demo-charts/line.mdx
- website/docs/tutorials/demo-charts/range.mdx
> Refactor refactor line, area, range, column, and bar charts based on XY chart.
> refactor(xy): line, area, range, column, and bar charts

- src/components/chart/chart.ts
- src/components/gauge-chart/gauge-chart.options.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.ts
- src/components/xy-chart/xy-chart.ts
- src/core/chart-options.ts
- src/core/utils.ts
- src/lib/area/area.ts
- src/lib/bar/bar.ts
- src/lib/charts.ts
- src/lib/column/column.ts
- src/lib/line/line.ts
- src/lib/range/range.ts
- src/lib/xy/xy.ts
- src/types/chart.types.ts
- website/docs/tutorials/demo-charts/bar.mdx
- website/docs/tutorials/demo-charts/donut.mdx
> refactor(core): simplify some configuration

- src/components/gauge-chart/gauge-chart.options.ts
- src/components/gauge-chart/gauge-chart.ts
- src/components/gauge-chart/gauge-chart.types.ts
- src/components/pie-chart/pie-chart.options.ts
- src/components/pie-chart/pie-chart.ts
- src/components/xy-chart/xy-chart.options.ts
- src/components/xy-chart/xy-chart.ts
- src/core/chart-options.ts
- src/lib/xy/xy.options.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- src/types/chart.types.ts
- src/types/common.types.ts
> refactor(core): finalize some chart options

- src/lib/xy/xy.options.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- website/docs/tutorials/demo-charts/bar.mdx
- website/docs/tutorials/demo-charts/column.mdx
- website/docs/tutorials/demo-charts/line.mdx
- website/docs/tutorials/demo-charts/range.mdx
> Support multiple value axes for XYChart.
> feat(xy): support multiple value axes for XYChart

- src/lib/area/area.ts
- src/lib/line/line.ts
- src/lib/range/range.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
> Refactor the way to set the color of XY chart
> refactor(xy): refactor the way to set the color of XY chart

- src/lib/.internal/chart.ts
- src/lib/charts.ts
- src/lib/gauge/gauge.ts
- src/lib/gauge/gauge.type.ts
- src/lib/gauge/index.ts
- src/types/font.types.ts
- website/docs/tutorials/demo-charts/gauge.mdx
> The gauge chart implementation was refactored and called through unified labels
> refactor(gauge): reconstructs the gauge chart implementation

- src/lib/gauge/gauge.ts
>  optimize some code specifications and writing
> refactor(gauge): optimize some code specifications and writing

- src/lib/gauge/gauge.ts
- src/lib/gauge/gauge.type.ts
- website/docs/tutorials/demo-charts/gauge.mdx
> fix(gauge): fix some bug for gauge chart

- src/lib/gauge/gauge.ts
> gauge chart data scales support array
> feat(gauge): support array for scales

- src/lib/legend/legend.ts
- src/lib/pie/pie.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- src/types/chart.legend.types.ts
- src/types/chart.types.ts
- website/docs/tutorials/demo-charts/line.mdx
> Support custom point style configuration.
> feat(legend): support customizing marker icon of legend item

- src/core/settings.ts
- src/core/utils.ts
- src/helpers/data.ts
- src/helpers/index.ts
- src/lib/.internal/chart.ts
- src/lib/donut/donut.ts
- src/types/chart.types.ts
- test/chart.spec.ts
- test/helpers/data.spec.ts
- website/docs/tutorials/demo-charts/donut.mdx
> feat: support number format and center labels refining for donut

- src/components/chart/chart.ts
- src/helpers/data.ts
- src/helpers/utils.ts
- src/lib/index.ts
- src/lib/legend/legend.ts
- src/lib/pie/pie.ts
- src/lib/xy/index.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- src/types/chart.event.types.ts
- src/types/chart.types.ts
- website/docs/tutorials/demo-charts/area.mdx
- website/docs/tutorials/demo-charts/bar.mdx
- website/docs/tutorials/demo-charts/column.mdx
- website/docs/tutorials/demo-charts/line.mdx
- website/docs/tutorials/demo-charts/mixed.mdx
- website/docs/tutorials/demo-charts/range.mdx
> fix(xy): fix some XY chart issues

- .github/workflows/pr-checks.yml
- package.json
> Checks for Pull Request

- package-lock.json
- package.json
- src/components/chart/chart.ts
- src/lib/.internal/chart.ts
- src/lib/donut/donut.ts
- src/lib/gauge/gauge.ts
- src/lib/pie/pie.ts
- src/lib/word-cloud/word-cloud.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- src/types/chart.event.types.ts
- src/types/chart.types.ts
- test/chart.spec.ts
- website/docs/tutorials/charts/bar.mdx
> Added mouse scrolling configuration and default display size configuration for bar chart.
> feat(xy): bar chart supports mouse scrolling

- src/lib/.internal/chart.ts
- src/lib/donut/donut.ts
- src/lib/pie/pie.ts
- src/lib/xy/xy.ts
- src/lib/xy/xy.types.ts
- src/types/chart.types.ts
- website/docs/tutorials/charts/column.mdx
- website/docs/tutorials/charts/donut.mdx
- website/docs/tutorials/charts/range.mdx
> Calculate the number of ticks based on canvas height
> feat(xy): calculate the number of ticks based on canvas height

- src/components/chart/chart.ts
- src/core/settings.ts
- src/core/theme-schema.ts
- src/lib/.internal/chart.ts
- src/lib/donut/donut.ts
- src/lib/gauge/gauge.ts
- src/lib/legend/legend.ts
- src/lib/pie/pie.ts
- src/lib/tooltip/tooltip.ts
- src/lib/tooltip/tooltip.types.ts
- src/lib/xy/xy.ts
- src/types/chart.event.types.ts
- src/types/chart.types.ts
> Chart lib support change theme by option and event.
> wip(theme): support theme customization (dark mode)

- src/charts/.internal/chart.ts
- src/charts/gauge/gauge.ts
- src/charts/pie/pie.ts
- src/charts/xy/xy.ts
- src/core/plugins/chart-a11y.ts
- src/core/plugins/chart-legend-a11y.ts
- src/core/plugins/index.ts
>  charts support accessibility event
> feat(a11y): for all charts

- src/charts/.internal/chart.ts
- src/charts/xy/xy.bar-scrollable.ts
- src/charts/xy/xy.category-label-selectable.ts
- src/charts/xy/xy.ts
- src/charts/xy/xy.types.ts
- src/components/chart/chart.ts
- src/core/themes.ts
- src/types/chart.event.types.ts
- website/docs/tutorials/charts/bar.mdx
> When maxLabels is configured, if the data length is larger than maxLabels, add a scrollbar effect to the bar chart.
> feat(xy): add scrollbar to bar chart

- src/charts/xy/xy.ts
- src/charts/xy/xy.types.ts
> Only one point needs to be displayed in the center of the chart
> fix(xy): only one point needs to be displayed in the center of the chart

- src/charts/.plugins/a11y/a11y-chart.ts
> fix chart color loss issue after clicking
> fix(a11y): fix chart color loss issue after clicking

- src/charts/pie/pie.ts
- src/charts/pie/pie.types.ts
> Add outRadius setting for pie chart
> feat(pie): add outRadius setting for pie chart

- src/charts/tooltip/tooltip.ts
> fix(tooltip): set line height of tooltip

- src/charts/legend/legend.ts
- src/charts/tooltip/tooltip.helper.ts
- src/charts/tooltip/tooltip.style.ts
- src/charts/tooltip/tooltip.ts
- src/charts/tooltip/tooltip.types.ts
- src/charts/xy/xy.category-tooltip.ts
- src/charts/xy/xy.ts
- src/charts/xy/xy.types.ts
- src/types/chart.legend.types.ts
- src/types/chart.types.ts
- website/docs/tutorials/advanced/tooltip.mdx
- website/docs/tutorials/charts/pie.mdx
> Add tooltips to category labels and legends. Tooltip supports custom title, body, and footer.
> The label of the category axis needs to set the labelTooltip configuration item to enable tooltips.
> The legend needs to set the tooltip configuration item to enable tooltips.
Tooltip of category label
Tooltip of legend
<p float="left">
</p>
> feat(tooltip): add tooltips to category labels and legends

- .vscode/settings.json
- rollup.config.ts
- src/charts/donut/donut.ts
- src/charts/legend/legend.ts
- src/charts/tooltip/tooltip.helper.ts
- src/charts/tooltip/tooltip.ts
- src/charts/tooltip/tooltip.types.ts
- src/charts/xy/xy.category-label-selectable.ts
- src/charts/xy/xy.category-tooltip.ts
- src/charts/xy/xy.ts
- src/charts/xy/xy.types.ts
- src/types/chart.event.types.ts
- src/types/chart.legend.types.ts
- src/types/chart.types.ts
- website/docs/tutorials/advanced/tooltip.mdx
- website/docs/tutorials/charts/pie.mdx
- website/docusaurus.js
> release the next alpha version
